- name: Creating user group
  group:
    name: '{{ drs_user }}'
    gid: "{{ drs_gid|default(omit) }}"
    state: present

- name: Creating user
  user:
    name: '{{ drs_user }}'
    password: '{{ drs_pass|default(omit) }}'
    group: '{{ drs_user }}'
    home: "{{drs_home_dir|default(omit)}}"
    shell: /bin/bash
    groups: sudo
    uid: "{{drs_uid|default(omit)}}"

- name: Adding to sudoers
  lineinfile: dest='/etc/sudoers' state='present' regexp='^{{drs_user}} ' line='{{drs_user}} ALL=(ALL:ALL) NOPASSWD:ALL'

